HTML:
  - changed-files:
      - any-glob-to-any-file: "**/*.html"

Python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"

Markdown:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"
