[phases.setup]
aptPkgs = [
  "mariadb-server", 
  "libmariadb-dev", 
  "python3-dev", 
  "build-essential", 
  "pkg-config"
]

[start]
cmds = ["python3 -m waitress --port=8080 --call app:create_app"]

