name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install pylint-flask
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=9.85 --load-plugins pylint_flask --max-line-length=410 --disable=C0411,C0114,W0401,C0116,W0614,E1101,W0612,R1702,W0611,R0912,C0412,W0101,C0302,C0115,C0121,E0704 $(git ls-files '*.py')
